test: use an image with curl for testing

diff --git a/kubernetes-manifests/loadgenerator.yaml b/kubernetes-manifests/loadgenerator.yaml
--- a/kubernetes-manifests/loadgenerator.yaml
+++ b/kubernetes-manifests/loadgenerator.yaml
@@ -31,9 +31,21 @@ spec:
       terminationGracePeriodSeconds: 5
       restartPolicy: Always
       initContainers:
-      - name: wait-for-frontend
-        image: busybox:1.28
-        command: ['sh', '-c', 'STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} -O tmp.file 2>&1 | grep -c "HTTP/1.1 200 OK"); test $STATUSCODE -eq 1']
+      - command:
+        - /bin/bash
+        - -exc
+        - |
+          echo "Ping Frontend: ${FRONTEND_ADDR}"
+          STATUSCODE=$(curl --silent --output /dev/stderr --write-out "%{http_code}" http://${FRONTEND_ADDR})
+          if test $STATUSCODE -ne 200; then
+              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
+              exit 1
+          fi
+        name: frontend-check
+        image: ellerbrock/alpine-bash-curl-ssl:latest
+        env:
+        - name: FRONTEND_ADDR
+          value: "frontend:80"
       containers:
       - name: main
         image: loadgenerator
