Release/v0.10.0 (#2507)
* Release v0.10.0

* Update Helm templates

* Package Helm chart

* Updated the releasing docs

* Update copyright headers

* Tweak releasing README

diff --git a/kustomize/base/loadgenerator.yaml b/kustomize/base/loadgenerator.yaml
--- a/kustomize/base/loadgenerator.yaml
+++ b/kustomize/base/loadgenerator.yaml
@@ -42,12 +42,20 @@ spec:
         - /bin/sh
         - -exc
         - |
-          echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
-          STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
-          if test $STATUSCODE -ne 200; then
-              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
-              exit 1
-          fi
+          MAX_RETRIES=12
+          RETRY_INTERVAL=10
+          for i in $(seq 1 $MAX_RETRIES); do
+            echo "Attempt $i: Pinging frontend: ${FRONTEND_ADDR}..."
+            STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
+            if [ $STATUSCODE -eq 200 ]; then
+                echo "Frontend is reachable."
+                exit 0
+            fi
+            echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
+            sleep $RETRY_INTERVAL
+          done
+          echo "Failed to reach frontend after $MAX_RETRIES attempts."
+          exit 1
         name: frontend-check
         securityContext:
           allowPrivilegeEscalation: false
@@ -69,7 +77,7 @@ spec:
               - ALL
           privileged: false
           readOnlyRootFilesystem: true
-        image: gcr.io/google-samples/microservices-demo/loadgenerator:v0.9.0
+        image: gcr.io/google-samples/microservices-demo/loadgenerator:v0.10.0
         env:
         - name: FRONTEND_ADDR
           value: "frontend:80"
